mode: learning
media_root: media
media_url: /media
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    # Plugins needed for the advances section.
    - hyde.ext.plugins.grouper.GrouperPlugin
context:
    data:
        author:
            name: Merlin Rebrović
            url: "http://merlin.rebrovic.net"
        layout:
            name: Hyde Starter Kit
            url: "https://github.com/merlinrebrovic/hyde-starter-kit"
        project:
            name: Hyde
            url: "http://hyde.github.com"
            install: "http://hyde.github.com/install.html"
        menu:
          - title: Home
            url: index.html
          - title: What next
            url: what-next.html
          - title: About
            url: about.html

### Advanced part ###

# This defines meta data on the whole site.
meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml

grouper:
    level:
        description: Difficulty levels
        groups:
            - name: basic
              description: Basic
            - name: advanced
              description: Advanced

